## Metadata

title:       Bones
description: Bones is a tiny CSS starting point with just the basics.
author:      Adam Hollett
url:         https://bones.netlify.com


## Locations

includes_dir: .


## Build settings

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - readme.md
sass:
  sass_dir: _assets/css


## Defaults

defaults:
  - scope:
      path: '' # all files in the project
    values:
      layout: default
