## Metadata

title:       Bones
description: Bones is a tiny CSS starting point with just the basics.
author:      Adam Hollett
url:         https://bones.netlify.com


## Locations

includes_dir: .
layouts_dir: .


## Build settings

incremental: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - readme.md

liquid:
  error_mode: strict


## Defaults

defaults:
  - scope:
      path: '' # all files in the project
    values:
      layout: layout
