title:       Bones
description: Bones is a tiny CSS starting point with just the basics.
author:      Adam Hollett
url:         https://bones.netlify.com

includes_dir: .
layouts_dir: .

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - readme.md

liquid:
  error_mode: strict

defaults:
  - scope:
      path: '' # all files in the project
    values:
      layout: layout
